enableGlobalCache: true

nodeLinker: node-modules

packageExtensions:
  apollo-engine-reporting-protobuf@*:
    dependencies:
      long: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-stage.cjs
    spec: "@yarnpkg/plugin-stage"

#pnpMode: loose

yarnPath: .yarn/releases/yarn-2.3.3.cjs
